# Generated by Django 5.2 on 2025-04-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginaudittrail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loginaudittrail',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='loginaudittrail',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalLoginAuditTrail',
        ),
        migrations.DeleteModel(
            name='LoginAuditTrail',
        ),
    ]
